# Generated by Django 4.2.3 on 2025-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_projects_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='my_photo.png', null=True, upload_to=''),
        ),
    ]
