# Generated by Django 4.2.3 on 2025-02-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_projects_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='avatar',
            field=models.ImageField(blank=True, default='salems.png', null=True, upload_to=''),
        ),
    ]
