# Generated by Django 4.2.3 on 2025-02-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='skills',
        ),
    ]
